name: Tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Django 4.2
          - django-version: "4.2"
            python-version: "3.8"
          - django-version: "4.2"
            python-version: "3.9"
          - django-version: "4.2"
            python-version: "3.10"
          - django-version: "4.2"
            python-version: "3.11"
          - django-version: "4.2"
            python-version: "3.12"

          # Django 5.0
          - django-version: "5.0"
            python-version: "3.10"
          - django-version: "5.0"
            python-version: "3.11"
          - django-version: "5.0"
            python-version: "3.12"

          # Django 5.1
          - django-version: "5.1"
            python-version: "3.10"
          - django-version: "5.1"
            python-version: "3.11"
          - django-version: "5.1"
            python-version: "3.12"
          - django-version: "5.1"
            python-version: "3.13"


    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip version
      run: python -m pip install -U pip

    - name: Install dev requirements
      run: python -m pip install -r requirements_dev.txt

    - name: Upgrade django version
      run: python -m pip install "Django~=${{ matrix.django-version }}"

    - name: Install reverse_relationship
      run: python -m pip install -e .

    - name: Run Tests
      run: |
        make test
